### ISSUE TITLE
feature: import external files or project manager

### ISSUE THREAD

**Issue by 1moita** [fabiosvm/hook-lang#43]
the issue title is self explanatory

**Comment by fabiosvm** [comment]
Hi, @1moita! Thanks for u issue.

This is a big important feature that Hook is missing. I think Hook needs both: importing external files and a package manager. I have some ideas, maybe you can help me decide which one to choose.

**Comment by fabiosvm** [comment]
Let's divide and conquer. For the issue of importing external files, for now, let's do something similar to what Lua does.

The interpreter will load Hook modules or native modules (shared libraries written in another language) depending on a list of patterns that can be customized by the `HOOK_PATH` environment variable.

The list of patterns is a string with substrings separated by `;`. And each substring is a pattern containing `?` which means the name of the module. Example:

```
?.hk;?/main.hk
```
In this case, the interpreter is being instructed to try to load first a `.hk` file in the current folder (same folder as the file that is importing the other one) and, then, the `main.hk` file in a folder inside the folder current.

For example, given the following code snippet:

```js
import my_module;
```

our list of patterns will resolve to:

* my_module.hk
* my_module/main.hk

A simple overview of the steps for the `VM` to take to load a module would be:

1) Given the list of patterns (taken from the environment variable or a default value), resolve each pattern with the module name and use the first match;
2) If the module has already been loaded, return it from cache;
3) If the module is not loaded, do it according to the file extension;
4) Update the cache and return the module;
