### ISSUE TITLE
feature: add include option to hook command line

### ISSUE THREAD

**Issue by 1moita** [fabiosvm/hook-lang#46]
will help in the import statement, to not be
```
import "modules/http/mod.hk"
```
but
```
import http
```

the option could be like `-I"modules/"`, so, the compiler will interpret **http** as `modules/http/mod.hk` (for an example).
this can be treated like a module manager.

treat this as an example feature, can be adapted to work better.

**Comment by fabiosvm** [comment]
Hi, @1moita. A module loading mechanism similar to Lua's has been implemented which allows customizing how to look for the module to be loaded.

This is done by modifying the `HOOK_PATH` environment variable. In your example, if you modify `HOOK_PATH` like this

```
export HOOK_PATH="$HOOK_PATH;modules/?/mod.hk"
```

the example `import http;` will work.

**Comment by fabiosvm** [comment]
I guess I helped. I'm closing the issue.
